namespace Aldsoft.Acord.LA
{
	using System.Collections.Generic;

	public class Relation
    {
        public string OriginatingObjectType { get; set; }
        public string RelatedObjectType { get; set; }
        public string RelationTypeCode { get; set; }
        public string ReciprocalRelationTypeCode { get; set; }

		public static Dictionary<string, Relation[]> AllowedRelationships = new Dictionary<string, Relation[]>
        {
			{ OLI_LU_REL.OLI_REL_TASK.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_TASK.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_ACTIVITY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_ACTIVITY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_TASK.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_ORIGINATOR.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_ORIGINATOR.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_ACTIVITY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_ORIGINATOR.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_PERFORMER.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_PERFORMER.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_ACTIVITY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_PERFORMER.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_RECIPIENT.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_RECIPIENT.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_ACTIVITY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_RECIPIENT.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_TARGET.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_TARGET.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_ACTIVITY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_TARGET.tc,  },  } },
			{ OLI_LU_REL.OLI_OTHER.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_OTHER.tc,  },  } },
			{ OLI_LU_REL.OLI_UNKNOWN.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_UNKNOWN.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_PHYSICALTHERAPIST.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_PHYSICALTHERAPIST.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_DISABILITYHEALTH.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_SKILLEDNURSE.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_SKILLEDNURSE.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_DISABILITYHEALTH.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_DISTRIBAGMT.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_DISTRIBAGMT.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_DISTRIBUTATIONAGREEMENT.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_DISTRIBAGMT.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_ADDTOFORM.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_ADDTOFORM.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_INCLUDEFORM.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_ATTACHEDFORM.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_ATTACHEDFORM.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_ATTACHEDTOFORM.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_ATTACHEDTOFORM.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_ATTACHEDTOFORM.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_ATTACHEDFORM.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_INCLUDEFORM.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_INCLUDEFORM.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_ADDTOFORM.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_CRFOR.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_CRFOR.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_CRFOR.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_CRFOR.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_CRFOR.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_FORMFOR.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_FORMFOR.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_FORMFOR.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_FORMFOR.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_FORMFOR.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_FORMFOR.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_HOLDING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_FORMFOR.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_FORMFOR.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_HOLDING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_FORMINSTANCE.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_FORMFOR.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_ASSOCIATEMEMBER.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_ASSOCIATEMEMBER.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_GROUP.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_EXPGROUP.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_EXPGROUP.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_EXPGROUP.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_EXPGROUP.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_EXPGROUP.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_GROUP.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_GROUP.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_GRPMEMBER.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_GROUP.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_GRPCONTACT.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_GROUP.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_MEMBER.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_GROUP.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_ASSOCIATEMEMBER.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_GRPCONTACT.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_GRPCONTACT.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_GROUP.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_GRPMEMBER.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_GRPMEMBER.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_GROUP.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_HOUSEHOLD.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_HOUSEHOLD.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_HOUSEHOLD.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_HOUSEHOLD.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_HOUSEHOLD.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_HHHEAD.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_HHHEAD.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_HHHEAD.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_HHHEAD.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_HHHEAD.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_HHMEMBER.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_HHMEMBER.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_HHMEMBER.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_HHMEMBER.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_PARTY.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_HHMEMBER.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_CAMPAIGN.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_CAMPAIGN.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_HOLDING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_CAMPAIGN.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_CAMPAIGN.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_CAMPAIGN.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_CAMPAIGN.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_HOLDING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_CAMPAIGN.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_CASE.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_CASE.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_HOLDING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_CASE.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_CASE.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_CASE.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_CASE.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_HOLDING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_CASE.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_SETTLEMENTCASE.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_SETTLEMENTCASE.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_HOLDING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_CASE.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_SETTLEMENTCASE.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_SETTLEMENTCASE.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_CASE.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_HOLDING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_SETTLEMENTCASE.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_MARKETINGTEAM.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_MARKETINGTEAM.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_HOLDING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_MARKETINGTEAM.tc,  }, new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_MARKETINGTEAM.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_GROUPING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_HOLDING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_MARKETINGTEAM.tc,  },  } },
			{ OLI_LU_REL.OLI_REL_ADDHOLDING.tc, new[]{ new Relation{ RelationTypeCode = OLI_LU_REL.OLI_REL_ADDHOLDING.tc, OriginatingObjectType = OLI_LU_OBJECTTYPE.OLI_HOLDING.tc, RelatedObjectType = OLI_LU_OBJECTTYPE.OLI_HOLDING.tc, ReciprocalRelationTypeCode = OLI_LU_REL.OLI_REL_ORIGADDHOLDING.tc,  },  } },
		};
	} // End Relation
} // End Namespace

