name: build

on:
  workflow_dispatch:
  push:
    branches:
    - master

    paths:
    - .github/workflows/build.yml
    - src/**

  pull_request:
    branches:
    - main

    paths:
    - .github/workflows/build.yml
    - src/**

jobs:
  test:
    runs-on: windows-2022
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v4

    # - name: 'Set up .NET Core'
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 8.0.x

    # - name: Install .NET Aspire workload
    #   run: dotnet workload install aspire

    - name: 'Restore dependencies'
      run: dotnet restore src/Aldsoft.Acord.sln

    - name: 'Build'
      run: dotnet build src/Aldsoft.Acord.sln --no-restore

    - name: 'Test'
      run: dotnet test src/Aldsoft.Acord.sln --no-build --no-restore --logger trx

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.17.0
      if: always()
      with:
        files: |
          src/**/TestResults/**/*.xml
          src/**/TestResults/**/*.trx
          src/**/TestResults/**/*.json
